spring:
  datasource:
    url: jdbc:postgresql://dpg-d60adbsr85hc73esusqg-a.virginia-postgres.render.com/ae_sports
    driver-class-name: org.postgresql.Driver
    username: ae_sports_user
    password: K3eQKSS8BImPnzSRWak1PKEVsYaFaFNy

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
